services:
  data_operations:
    build:
      context: .
      dockerfile: services/data_operations/Dockerfile
    container_name: data_operations
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
      - ./storage:/app/storage
    environment:
      - DATASET_ROOT=/app/dataset
      - STORAGE_ROOT=/app/storage
      - TZ=Europe/Budapest

  defect_detection:
    build:
      context: .
      dockerfile: services/defect_detection/Dockerfile
    container_name: defect_detection
    ports:
      - "8001:8000"
    volumes:
      - ./dataset:/app/dataset
      - ./storage:/app/storage
    environment:
      - DATASET_ROOT=/app/dataset
      - STORAGE_ROOT=/app/storage
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/0
      - TZ=Europe/Budapest
    shm_size: "16gb"
    depends_on:
      - redis_broker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis_broker:
    image: redis:7-alpine
    container_name: defect_detection_redis
    restart: unless-stopped

  defect_detection_worker:
    build:
      context: .
      dockerfile: services/defect_detection/Dockerfile
    container_name: defect_detection_worker
    command: celery -A services.defect_detection.tasks.celery_app worker --loglevel=info -c 1
    volumes:
      - ./dataset:/app/dataset
      - ./storage:/app/storage
    environment:
      - DATASET_ROOT=/app/dataset
      - STORAGE_ROOT=/app/storage
      - CELERY_BROKER_URL=redis://redis_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_broker:6379/0
      - TZ=Europe/Budapest
    shm_size: "16gb"
    depends_on:
      - redis_broker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: defect_detection_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      - VITE_API_BASE_URL=http://localhost:8001

    restart: unless-stopped

    depends_on:
      - data_operations
      - defect_detection
