import torch.nn as nn


class AutoEncoder(nn.Module):
    def __init__(self, cfg: dict):
        super(AutoEncoder, self).__init__()

        # E N C O D E R
        self.encoder = nn.Sequential(
            nn.Conv2d(in_channels=cfg.get("input_channel"),
                      out_channels=cfg.get("flc"),
                      kernel_size=cfg.get("kernel_size")[1],
                      stride=cfg.get("stride")[1],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("flc"),
                      kernel_size=cfg.get("kernel_size")[1],
                      stride=cfg.get("stride")[1],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("flc"),
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("flc") * 2,
                      kernel_size=cfg.get("kernel_size")[1],
                      stride=cfg.get("stride")[1],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 2,
                      out_channels=cfg.get("flc") * 2,
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 2,
                      out_channels=cfg.get("flc") * 4,
                      kernel_size=cfg.get("kernel_size")[1],
                      stride=cfg.get("stride")[1],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 4,
                      out_channels=cfg.get("flc") * 2,
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 2,
                      out_channels=cfg.get("flc"),
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("latent_space_dimension"),
                      kernel_size=cfg.get("kernel_size")[2],
                      stride=cfg.get("stride")[0])
        )

        # D E C O D E R
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(in_channels=cfg.get("latent_space_dimension"),
                               out_channels=cfg.get("flc"),
                               kernel_size=cfg.get("kernel_size")[2],
                               stride=cfg.get("stride")[0]),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("flc") * 2,
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 2,
                      out_channels=cfg.get("flc") * 4,
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.ConvTranspose2d(in_channels=cfg.get("flc") * 4,
                               out_channels=cfg.get("flc") * 2,
                               kernel_size=cfg.get("kernel_size")[1],
                               stride=cfg.get("stride")[1],
                               padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc") * 2,
                      out_channels=cfg.get("flc") * 2,
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.ConvTranspose2d(in_channels=cfg.get("flc") * 2,
                               out_channels=cfg.get("flc"),
                               kernel_size=cfg.get("kernel_size")[1],
                               stride=cfg.get("stride")[1],
                               padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.Conv2d(in_channels=cfg.get("flc"),
                      out_channels=cfg.get("flc"),
                      kernel_size=cfg.get("kernel_size")[0],
                      stride=cfg.get("stride")[0],
                      padding=cfg.get("padding")),
            nn.LeakyReLU(negative_slope=cfg.get("alpha_slope")),
            nn.ConvTranspose2d(in_channels=cfg.get("flc"),
                               out_channels=cfg.get("input_channel"),
                               kernel_size=cfg.get("kernel_size")[1],
                               stride=cfg.get("stride")[1],
                               padding=cfg.get("padding")),
            nn.Sigmoid()
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        decoded = nn.functional.interpolate(decoded, size=(128, 128), mode='bilinear', align_corners=False)
        return decoded
